services:
  postgres:
    image: postgres:alpine
    container_name: payment_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    expose:
      - 5432
    volumes:
      - payment_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: payment_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - 6379
    volumes:
      - payment_redis_data:/data

volumes:
  payment_pg_data:
  payment_redis_data:

networks:
  default:
    name: internal_vpc
    external: true