app:
  port: YOUR_APP_PORT

database:
  host: YOUR_DB_HOST
  user: YOUR_DB_USER
  password: YOUR_DB_PASSWORD
  name: YOUR_DB_NAME
  port: YOUR_DB_PORT

redis:
  host: YOUR_REDIS_HOST
  password: YOUR_REDIS_PASSWORD
  port: YOUR_REDIS_PORT

secret:
  jwt_secret_key: YOUR_JWT_SECRET_KEY

kafka:
  broker: YOUR_KAFKA_BROKER_HOST_PORT
  topics:
    - order.created: order.created
    - payment.success: payment.success

xendit:
  secret_api_key: "YOUR_XENDIT_API_KEY"
  webhook_token: "YOUR_XENDIT_WEBHOOK_TOKEN"

toggle:
  disable_create_invoice_directly: true